# Generated by Django 3.2.11 on 2022-01-17 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicioeeg',
            fields=[
                ('idEjercicioeeg', models.BigAutoField(primary_key=True, serialize=False)),
                ('idEjercicios', models.IntegerField()),
                ('idPaciente', models.IntegerField()),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.CharField(default='sin', max_length=4)),
                ('banda', models.CharField(default='sin', max_length=10)),
                ('fechaActividad', models.DateTimeField()),
                ('valor', models.FloatField(default=0)),
                ('eliminado', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicioeeg', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fechaRegistro'],
            },
        ),
    ]
