# Generated by Django 3.2.11 on 2022-01-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicioeeg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicioeeg',
            name='calculado1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ejercicioeeg',
            name='calculado2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ejercicioeeg',
            name='calculado3',
            field=models.FloatField(default=0),
        ),
    ]
