# Generated by Django 3.2.11 on 2022-01-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicioeeg', '0002_auto_20220123_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejercicioeeg',
            name='banda',
        ),
        migrations.RemoveField(
            model_name='ejercicioeeg',
            name='fechaActividad',
        ),
        migrations.RemoveField(
            model_name='ejercicioeeg',
            name='sensor',
        ),
        migrations.RemoveField(
            model_name='ejercicioeeg',
            name='valor',
        ),
        migrations.AddField(
            model_name='ejercicioeeg',
            name='F3Alpha',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ejercicioeeg',
            name='F3BethaH',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ejercicioeeg',
            name='F3BethaL',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ejercicioeeg',
            name='F3Gamma',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ejercicioeeg',
            name='F3Theta',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ejercicioeeg',
            name='F4Alpha',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ejercicioeeg',
            name='F4BethaH',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ejercicioeeg',
            name='F4BethaL',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ejercicioeeg',
            name='F4Gamma',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ejercicioeeg',
            name='F4Theta',
            field=models.FloatField(default=0),
        ),
    ]
